apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gateway-oci-vault
  namespace: mcp-security-gateway
spec:
  provider: oci
  parameters:
    authType: instance
    secrets: |
      - name: gateway-upstream-token
        vaultId: ocid1.vault.oc1..<replace_me>
      - name: gateway-admin-token
        vaultId: ocid1.vault.oc1..<replace_me>
